services:
  api:
    image: clickbus:1.0
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    restart: on-failure
    networks:
      - private-net

  mysql:
    container_name: mysql
    image: mysql:9.0.1
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - private-net


networks:
  private-net:
    driver: bridge